### PR TITLE
Adds three kata

### PR DESCRIPTION
**Pull request by xpepper**
OCP Kata and Birthday Greetings Kata by Matteo Vaccari, Social Networking Kata by Sandro Mancuso

### CODE REVIEW

**Comment by xpepper** [comment]
@gamontalvo do you want me to create a new pull request on the new master branch? Or if you prefer I could solve the actual conflicts.... let me know. 👍

**Comment by gamontal** [comment]
Great, please feel free to solve the conflicts. Thanks!

**Comment by xpepper** [comment]
@gamontal fixed... you can merge it if you like it. 
Thanks

**Comment by gamontal** [comment]
Awesome, thanks! @xpepper

**Pull request merged**
